#!/usr/bin/env bash

confs=("0.981" "0.982" "0.983" "0.984" "0.985" "0.986" "0.987" "0.988" "0.989")

end=0
for cf in ${confs[@]}; do
    echo $end
    echo $cf
    python main.py $cf $end
    let "end=$end+1"
done
